name: main

on:
  workflow_dispatch: # manual override
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v2

      - name: get keyfile
        run: echo -e '${{ secrets.ARWEAVE_KEYFILE }}' > keyfile.json

      - name: run script
        # this should overwrite the "status.json" file
        # with the updated stutus on where we are on the curve
        run: node .

      - name: commit status file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update status
          file_pattern: status.json
