name: decay

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 * * * *" # every hour

jobs:
  decay:
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: setup deps
        run: npm install

      - name: get keyfile
        run: echo -e '${{ secrets.ARWEAVE_KEYFILE }}' > keyfile.json

      - name: radiate
        run: npm run start
        env:
          JWK: ${{ secrets.JWK }}

      - name: commit status file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update status
          file_pattern: status.json
